/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.Gerente;

import static controller.EfetuaConexao.conectaBanco;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ConexaoBD;
import model.Projeto;
import model.Tabela;
import view.Projetista.VwJIFProjetoProjetista;
import view.VwJIFInserirProjeto;
import java.lang.String;
import model.Constante;
/**
 *
 * @author Giovanni
 */
public class VwJIFGerenciaProjetoGerente extends javax.swing.JInternalFrame {

    private static VwJIFGerenciaProjetoGerente vwJIFGerenciaProjetoGerente;

    public static JInternalFrame getInstancia() {
        if(vwJIFGerenciaProjetoGerente == null){
            vwJIFGerenciaProjetoGerente = new VwJIFGerenciaProjetoGerente();
        }
        return vwJIFGerenciaProjetoGerente;
    }
    
    public VwJIFGerenciaProjetoGerente() {
        initComponents();
        mostra_projeto();
    }
    
     public ArrayList<Projeto> projetoList(){
        ArrayList<Projeto> projetosList = new ArrayList<>();
        try{
            ConexaoBD bd = new ConexaoBD();

            conectaBanco(Constante.servidor, bd, Constante.login, Constante.login);
            String sql="SELECT numero, data_inicio, data_termino, id_projetista, id_cliente, descricao FROM private.projeto \n" +
                        "ORDER BY numero;";
            
            ResultSet rs = bd.stmt.executeQuery(sql);
            Projeto projeto;
            while(rs.next()){
                projeto=new Projeto(rs.getInt("numero"), rs.getString("data_inicio"), rs.getString("data_termino"), rs.getInt("id_projetista"), rs.getInt("id_cliente"), rs.getString("descricao"));
                projetosList.add(projeto);
            }
            bd.Desconectar();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        return projetosList;     
    }

    /**
     *
     */
    public void mostra_projeto(){
        ArrayList<Projeto> list = projetoList();
        DefaultTableModel model = (DefaultTableModel)jt_MostraProjetosGerente.getModel();
        Object[] row = new Object[6];
        for(int i=0; i<list.size();i++){
            row[0]=list.get(i).getNumero();
            row[1]=list.get(i).getData_inicio();
            row[2]=list.get(i).getData_termino();
            row[3]=list.get(i).getId_projetista();
            row[4]=list.get(i).getId_cliente();
            row[5]=list.get(i).getDescricao();
            model.addRow(row);
        }
        Tabela.ordenaTabela(jt_MostraProjetosGerente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jtb_botoes = new javax.swing.JToolBar();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblIdCliente = new javax.swing.JLabel();
        lblIdProjetista = new javax.swing.JLabel();
        txtIdProjetista = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        lblDtaInicio = new javax.swing.JLabel();
        dc_Inicio = new com.toedter.calendar.JDateChooser();
        dc_Fim = new com.toedter.calendar.JDateChooser();
        lblDtaTermino = new javax.swing.JLabel();
        txtIdCliente = new javax.swing.JTextField();
        lblDescricao = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_MostraProjetosGerente = new javax.swing.JTable();
        txtNumProjeto = new javax.swing.JTextField();
        lblNumProjeto = new javax.swing.JLabel();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(46, 134, 222));

        lblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Gerenciamento de Projetos");

        jtb_botoes.setFloatable(false);
        jtb_botoes.setRollover(true);

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/novo.png"))); // NOI18N
        btnNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNovoMouseClicked(evt);
            }
        });
        jtb_botoes.add(btnNovo);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editar.png"))); // NOI18N
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
        });
        jtb_botoes.add(btnEditar);

        btnDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/remover.png"))); // NOI18N
        btnDeletar.setFocusable(false);
        btnDeletar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeletar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDeletar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeletarMouseClicked(evt);
            }
        });
        jtb_botoes.add(btnDeletar);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblTitulo)
                .addGap(115, 115, 115)
                .addComponent(jtb_botoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtb_botoes, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        lblIdCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblIdCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblIdCliente.setText("ID Cliente:");

        lblIdProjetista.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblIdProjetista.setForeground(new java.awt.Color(255, 255, 255));
        lblIdProjetista.setText("ID Projetista:");

        txtIdProjetista.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtIdProjetista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProjetistaActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 153, 153));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalvar.setBackground(new java.awt.Color(153, 204, 255));
        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lblDtaInicio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDtaInicio.setForeground(new java.awt.Color(255, 255, 255));
        lblDtaInicio.setText("Data início:");

        dc_Inicio.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        dc_Fim.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        lblDtaTermino.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDtaTermino.setForeground(new java.awt.Color(255, 255, 255));
        lblDtaTermino.setText("Data término:");

        txtIdCliente.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtIdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdClienteActionPerformed(evt);
            }
        });

        lblDescricao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDescricao.setForeground(new java.awt.Color(255, 255, 255));
        lblDescricao.setText("Descrição:");

        txtDescricao.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoActionPerformed(evt);
            }
        });

        jt_MostraProjetosGerente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "numero", "dta_inicio", "dta_termino", "id_projetista", "id_cliente", "descricao"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jt_MostraProjetosGerente.setAutoscrolls(false);
        jt_MostraProjetosGerente.setShowGrid(false);
        jt_MostraProjetosGerente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_MostraProjetosGerenteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_MostraProjetosGerente);
        if (jt_MostraProjetosGerente.getColumnModel().getColumnCount() > 0) {
            jt_MostraProjetosGerente.getColumnModel().getColumn(0).setPreferredWidth(30);
            jt_MostraProjetosGerente.getColumnModel().getColumn(1).setPreferredWidth(100);
            jt_MostraProjetosGerente.getColumnModel().getColumn(2).setPreferredWidth(100);
            jt_MostraProjetosGerente.getColumnModel().getColumn(3).setPreferredWidth(50);
            jt_MostraProjetosGerente.getColumnModel().getColumn(4).setPreferredWidth(50);
            jt_MostraProjetosGerente.getColumnModel().getColumn(5).setPreferredWidth(350);
        }

        txtNumProjeto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtNumProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumProjetoActionPerformed(evt);
            }
        });

        lblNumProjeto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNumProjeto.setForeground(new java.awt.Color(255, 255, 255));
        lblNumProjeto.setText("Nº Projeto:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtDescricao, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblDtaInicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblIdProjetista, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtIdProjetista, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblNumProjeto, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNumProjeto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dc_Inicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblIdCliente)
                                        .addComponent(lblDtaTermino)
                                        .addComponent(dc_Fim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(btnCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblNumProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdProjetista, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdProjetista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDtaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDtaTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dc_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dc_Fim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelar)
                            .addComponent(btnSalvar))))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdProjetistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProjetistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProjetistaActionPerformed

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        this.desabilitaTxt();
        this.limparCampos();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
         String acaoBotao = Constante.cadastro;
        if(acaoBotao.equals("Novo")){
            try{
            ConexaoBD bd = new ConexaoBD();
            
            conectaBanco(Constante.servidor, bd, Constante.login, Constante.login);
            String sql="INSERT INTO private.projeto(data_inicio, data_termino, id_projetista, id_cliente, descricao)\n" +
                       "VALUES ('"+ dc_Inicio.getDate() +"','"+ dc_Fim.getDate() +"',"
                        + ""+ txtIdProjetista.getText() +","+ txtIdCliente.getText() +", '"+ txtDescricao.getText() +"')";
            
            bd.stmt.executeUpdate(sql);
            bd.Desconectar();
            
            
            JOptionPane.showMessageDialog(null, "Projeto cadastrado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            } 
           
        }else if(acaoBotao.equals("Alterar")){
            try{
                ConexaoBD bd = new ConexaoBD();
                
                conectaBanco(Constante.servidor, bd, Constante.login, Constante.login);
                String sql="UPDATE private.projeto SET data_inicio ='"+ dc_Inicio.getDate() + "', data_termino ='\n" +
                        dc_Fim.getDate() + "', id_projetista ='"+ txtIdProjetista.getText() + "', id_cliente ='\n" +
                        txtIdCliente.getText() + "', descricao ='" + txtDescricao.getText() + "' WHERE numero =" + txtNumProjeto.getText();
                
                bd.stmt.executeUpdate(sql);
                bd.Desconectar();
                
                JOptionPane.showMessageDialog(null, "Projeto atualizado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
          
                }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
                } 
            
        }else if(acaoBotao.equals("Deletar")){
            Object[]opcoes = {"Sim","Não"};
            int opcao = JOptionPane.showOptionDialog(null, "Tem certeza que deseja deletar esse Projeto?", "Aviso", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, opcoes, opcoes[0]);
        
            if(opcao == 0){
            try{
                ConexaoBD bd = new ConexaoBD();
                bd.Conectar("jdbc:postgresql://localhost:5432/projeto", "super", "super");
                
                String sql= "DELETE FROM private.projeto WHERE numero = " + txtNumProjeto.getText();
                bd.stmt.executeUpdate(sql);
                
                bd.Desconectar();
                JOptionPane.showMessageDialog(null, "Projeto deletado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                
                }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
             } 
           }   
        }
        
        this.atualizaDataTable();
        
        limparCampos();
        acaoBotao = "";
        this.desabilitaTxt();
    }//GEN-LAST:event_btnSalvarMouseClicked

    private void atualizaDataTable() {
        DefaultTableModel model = (DefaultTableModel) jt_MostraProjetosGerente.getModel();

        model.setRowCount(0);
        /**/
        ArrayList<Projeto> list = projetoList();

        Object[] row = new Object[6];
            for(int i=0; i<list.size();i++){
                row[0]=list.get(i).getNumero();
                row[1]=list.get(i).getData_inicio();
                row[2]=list.get(i).getData_termino();
                row[3]=list.get(i).getId_projetista();
                row[4]=list.get(i).getId_cliente();
                row[5]=list.get(i).getDescricao();
                model.addRow(row);
            }
        jt_MostraProjetosGerente.setModel(model);
  
        model.fireTableDataChanged();

}
    
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtIdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdClienteActionPerformed

    private void txtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoActionPerformed

    private void btnNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoMouseClicked
        this.habilitaTxt();
        Constante.cadastro = "Novo"; 
        limparCampos();
    }//GEN-LAST:event_btnNovoMouseClicked

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
        this.habilitaTxt();
        Constante.cadastro = "Alterar";
    }//GEN-LAST:event_btnEditarMouseClicked

    private void btnDeletarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeletarMouseClicked
        Constante.cadastro = "Deletar";
        this.btnSalvarMouseClicked(evt);
    }//GEN-LAST:event_btnDeletarMouseClicked

    private void txtNumProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumProjetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumProjetoActionPerformed

    private void jt_MostraProjetosGerenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_MostraProjetosGerenteMouseClicked
        int row = jt_MostraProjetosGerente.getSelectedRow();
        txtNumProjeto.setText(jt_MostraProjetosGerente.getValueAt(row, 0).toString());
        
        DateFormat format = new SimpleDateFormat("yyyy-MM-dd");
 
        try {
            dc_Inicio.setDate(format.parse(jt_MostraProjetosGerente.getValueAt(row, 1).toString()));
            dc_Fim.setDate(format.parse(jt_MostraProjetosGerente.getValueAt(row, 2).toString()));
        } catch (ParseException ex) {
            Logger.getLogger(VwJIFProjetoProjetista.class.getName()).log(Level.SEVERE, null, ex);
        }
 
        txtIdProjetista.setText(jt_MostraProjetosGerente.getValueAt(row, 3).toString());
        txtIdCliente.setText(jt_MostraProjetosGerente.getValueAt(row, 4).toString());
        txtDescricao.setText(String.valueOf(jt_MostraProjetosGerente.getValueAt(row, 5)));
        if (txtDescricao.getText().equals("null")){
            txtDescricao.setText("");
        }

    }//GEN-LAST:event_jt_MostraProjetosGerenteMouseClicked

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        this.txtNumProjeto.setEnabled(false);
        this.desabilitaTxt();
    }//GEN-LAST:event_formInternalFrameOpened
     
    private void habilitaTxt(){
        this.txtDescricao.setEnabled(true);
        this.dc_Inicio.setEnabled(true);
        this.dc_Fim.setEnabled(true);
        this.txtIdCliente.setEnabled(true);
        this.txtIdProjetista.setEnabled(true);
      
    }
    
    private void desabilitaTxt(){
        this.txtDescricao.setEnabled(false);
        this.dc_Inicio.setEnabled(false);
        this.dc_Fim.setEnabled(false);
        this.txtIdCliente.setEnabled(false);
        this.txtIdProjetista.setEnabled(false);
    }
    
    private void limparCampos(){
        this.txtDescricao.setText("");
        this.dc_Inicio.setDate(null);
        this.dc_Fim.setDate(null);
        this.txtIdCliente.setText("");
        this.txtIdProjetista.setText("");
        this.txtNumProjeto.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private com.toedter.calendar.JDateChooser dc_Fim;
    private com.toedter.calendar.JDateChooser dc_Inicio;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jt_MostraProjetosGerente;
    private javax.swing.JToolBar jtb_botoes;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblDtaInicio;
    private javax.swing.JLabel lblDtaTermino;
    private javax.swing.JLabel lblIdCliente;
    private javax.swing.JLabel lblIdProjetista;
    private javax.swing.JLabel lblNumProjeto;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtIdProjetista;
    private javax.swing.JTextField txtNumProjeto;
    // End of variables declaration//GEN-END:variables
}
