/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.Gerente;

import com.sun.tools.javac.util.Name;
import static controller.EfetuaConexao.conectaBanco;
import java.awt.Color;
import java.sql.ResultSet;
import model.Projeto;
import java.util.ArrayList;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.ConexaoBD;
import model.Constante;
import model.Tabela;
import view.Projetista.VwJIFIdentificaProjetista;


/**
 *
 * @author Giovanni
 */
public class VwJIFRelatorioProjetoGerente extends javax.swing.JInternalFrame {

    private static VwJIFRelatorioProjetoGerente vwJIFRelatorioProjetoGerente;

    public static JInternalFrame getInstancia() {
        if(vwJIFRelatorioProjetoGerente == null){
            vwJIFRelatorioProjetoGerente = new VwJIFRelatorioProjetoGerente();
        }
        return vwJIFRelatorioProjetoGerente;
    }
    
    public VwJIFRelatorioProjetoGerente() {
        initComponents();
        mostra_projeto();
        mostraMediaTempoProjetos();
        atualizaDataTable();
    }
    
    public void mostraMediaTempoProjetos(){
        try{
            ConexaoBD bd = new ConexaoBD();
            conectaBanco(Constante.servidor, bd, Constante.login, Constante.login);
            String sql="SELECT * FROM private.media_tempo_projeto";
            ResultSet rs = bd.stmt.executeQuery(sql);
            Projeto projeto;
            while(rs.next()){
                txtMedia.setText(rs.getString("media_duracao_projeto").toString());
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        txtMedia.setEnabled(false);
        txtMedia.setDisabledTextColor(Color.black);
    }
  
    public ArrayList<Projeto> projetoList(){
        ArrayList<Projeto> projetosList = new ArrayList<>();
        try{
            ConexaoBD bd = new ConexaoBD();
            conectaBanco(Constante.servidor, bd, Constante.login, Constante.login);
            String sql="SELECT * FROM private.projeto";
            ResultSet rs = bd.stmt.executeQuery(sql);
            Projeto projeto;
            while(rs.next()){
                projeto=new Projeto(rs.getInt("numero"), rs.getString("data_inicio"), rs.getString("data_termino"), rs.getInt("id_projetista"), rs.getInt("id_cliente"), rs.getString("descricao"));
                projetosList.add(projeto);
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        return projetosList;     
    }

    
    
    public void mostra_projeto(){
        ArrayList<Projeto> list = projetoList();
        DefaultTableModel model = (DefaultTableModel)jt_MostraProjetosProjetista.getModel();
        Object[] row = new Object[6];
        for(int i=0; i<list.size();i++){
            row[0]=list.get(i).getNumero();
            row[1]=list.get(i).getData_inicio();
            row[2]=list.get(i).getData_termino();
            row[3]=list.get(i).getId_projetista();
            row[4]=list.get(i).getId_cliente();
            row[5]=list.get(i).getDescricao();
            model.addRow(row);
        }
        Tabela.ordenaTabela(jt_MostraProjetosProjetista);
    }
    
        private void atualizaDataTable() {
        DefaultTableModel model = (DefaultTableModel) jt_MostraProjetosProjetista.getModel();

        model.setRowCount(0);
        /**/
        ArrayList<Projeto> list = projetoList();

        Object[] row = new Object[6];
            for(int i=0; i<list.size();i++){
                row[0]=list.get(i).getNumero();
                row[1]=list.get(i).getData_inicio();
                row[2]=list.get(i).getData_termino();
                row[3]=list.get(i).getId_projetista();
                row[4]=list.get(i).getId_cliente();
                row[5]=list.get(i).getDescricao();
                model.addRow(row);
            }
        jt_MostraProjetosProjetista.setModel(model);
  
        model.fireTableDataChanged();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_MostraProjetosProjetista = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        lblMedia = new javax.swing.JLabel();
        txtMedia = new javax.swing.JTextField();
        lblBusca = new javax.swing.JLabel();
        txtBusca = new javax.swing.JTextField();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(46, 134, 222));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Relatório de Projetos");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/atualizar.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jt_MostraProjetosProjetista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "numero", "data_inicio", "data_termino", "id_projetista", "id_cliente", "descricao"
            }
        ));
        jt_MostraProjetosProjetista.setAutoscrolls(false);
        jt_MostraProjetosProjetista.setShowGrid(false);
        jScrollPane1.setViewportView(jt_MostraProjetosProjetista);
        if (jt_MostraProjetosProjetista.getColumnModel().getColumnCount() > 0) {
            jt_MostraProjetosProjetista.getColumnModel().getColumn(5).setPreferredWidth(350);
        }

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblMedia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMedia.setForeground(new java.awt.Color(255, 255, 255));
        lblMedia.setText("TEMPO MÉDIO DE DURAÇÃO TOTAL:");

        txtMedia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtMedia.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblBusca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBusca.setForeground(new java.awt.Color(255, 255, 255));
        lblBusca.setText("Buscar:");

        txtBusca.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblBusca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(lblMedia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 877, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaKeyPressed
        Tabela.buscaNaTabela(jt_MostraProjetosProjetista, txtBusca);
    }//GEN-LAST:event_txtBuscaKeyPressed

    private void txtBuscaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaKeyTyped

    }//GEN-LAST:event_txtBuscaKeyTyped

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
       
    }//GEN-LAST:event_formInternalFrameOpened

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        atualizaDataTable();
    }//GEN-LAST:event_jButton1MouseClicked

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed

    }//GEN-LAST:event_formInternalFrameClosed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing

    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jt_MostraProjetosProjetista;
    private javax.swing.JLabel lblBusca;
    private javax.swing.JLabel lblMedia;
    private javax.swing.JTextField txtBusca;
    private javax.swing.JTextField txtMedia;
    // End of variables declaration//GEN-END:variables
}
