/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.Projetista;

import static controller.EfetuaConexao.conectaBanco;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ConexaoBD;
import model.Constante;
import model.Projetista;
import model.Projeto;
import model.Tabela;

/**
 *
 * @author Giovanni
 */
public class VwJIFProjetoProjetista extends javax.swing.JInternalFrame {

    private String cod_funcional;
   
    Projetista projetista;
    

    public VwJIFProjetoProjetista(String cod) {
        initComponents();
        this.cod_funcional = cod;
        mostra_projeto();
 
    }
    
    public ArrayList<Projeto> projetoList(){
        ArrayList<Projeto> projetosList = new ArrayList<>();
        try{
            ConexaoBD bd = new ConexaoBD();
            
           
            conectaBanco(Constante.servidor, bd, Constante.login, Constante.login);
            String sql="SELECT numero, data_inicio, data_termino, id_projetista, id_cliente, descricao FROM private.projeto \n" +
                        "INNER JOIN private.projetista\n" +
                        "ON id = id_projetista\n" +
                        "WHERE cod_funcional="+ cod_funcional +" ORDER BY numero;";
            
            ResultSet rs = bd.stmt.executeQuery(sql);
            Projeto projeto;
            while(rs.next()){
                projeto=new Projeto(rs.getInt("numero"), rs.getString("data_inicio"), rs.getString("data_termino"), rs.getInt("id_projetista"), rs.getInt("id_cliente"), rs.getString("descricao"));
                projetosList.add(projeto);
            }
            bd.Desconectar();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        return projetosList;     
    }

    /**
     *
     */
    public void mostra_projeto(){
        ArrayList<Projeto> list = projetoList();
        DefaultTableModel model = (DefaultTableModel)jt_MostraProjetosProjetista.getModel();
        Object[] row = new Object[6];
        for(int i=0; i<list.size();i++){
            row[0]=list.get(i).getNumero();
            row[1]=list.get(i).getData_inicio();
            row[2]=list.get(i).getData_termino();
            row[3]=list.get(i).getId_projetista();
            row[4]=list.get(i).getId_cliente();
            row[5]=list.get(i).getDescricao();
            model.addRow(row);
        }
        Tabela.ordenaTabela(jt_MostraProjetosProjetista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jtb_botoes = new javax.swing.JToolBar();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_MostraProjetosProjetista = new javax.swing.JTable();
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblDtaInicio = new javax.swing.JLabel();
        lblDtaTermino = new javax.swing.JLabel();
        lblIdProjetista = new javax.swing.JLabel();
        txtIdProjetista = new javax.swing.JTextField();
        lblIdCliente = new javax.swing.JLabel();
        txtIdCliente = new javax.swing.JTextField();
        lblDescricao = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        dc_Inicio = new com.toedter.calendar.JDateChooser();
        dc_Fim = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(46, 134, 222));

        jtb_botoes.setFloatable(false);
        jtb_botoes.setRollover(true);

        btnNovo.setBackground(new java.awt.Color(0, 0, 0));
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/novo.png"))); // NOI18N
        btnNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNovoMouseClicked(evt);
            }
        });
        jtb_botoes.add(btnNovo);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editar.png"))); // NOI18N
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
        });
        jtb_botoes.add(btnEditar);

        btnDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/remover.png"))); // NOI18N
        btnDeletar.setFocusable(false);
        btnDeletar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeletar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDeletar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeletarMouseClicked(evt);
            }
        });
        jtb_botoes.add(btnDeletar);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Projetos do Projetista");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(67, 67, 67)
                .addComponent(jtb_botoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jtb_botoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jt_MostraProjetosProjetista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "num", "dta_inicio", "dta_termino", "id_projetista", "id_cliente", "descricao"
            }
        ));
        jt_MostraProjetosProjetista.setAutoscrolls(false);
        jt_MostraProjetosProjetista.setShowGrid(false);
        jt_MostraProjetosProjetista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_MostraProjetosProjetistaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_MostraProjetosProjetista);
        if (jt_MostraProjetosProjetista.getColumnModel().getColumnCount() > 0) {
            jt_MostraProjetosProjetista.getColumnModel().getColumn(0).setPreferredWidth(1);
            jt_MostraProjetosProjetista.getColumnModel().getColumn(1).setPreferredWidth(30);
            jt_MostraProjetosProjetista.getColumnModel().getColumn(2).setPreferredWidth(30);
            jt_MostraProjetosProjetista.getColumnModel().getColumn(3).setPreferredWidth(15);
            jt_MostraProjetosProjetista.getColumnModel().getColumn(4).setPreferredWidth(15);
        }

        lblNumero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNumero.setForeground(new java.awt.Color(255, 255, 255));
        lblNumero.setText("Número:");

        txtNumero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });

        lblDtaInicio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDtaInicio.setForeground(new java.awt.Color(255, 255, 255));
        lblDtaInicio.setText("Dta Início:");

        lblDtaTermino.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDtaTermino.setForeground(new java.awt.Color(255, 255, 255));
        lblDtaTermino.setText("Dta_Término: ");

        lblIdProjetista.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblIdProjetista.setForeground(new java.awt.Color(255, 255, 255));
        lblIdProjetista.setText("ID Projetista:");

        txtIdProjetista.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtIdProjetista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProjetistaActionPerformed(evt);
            }
        });

        lblIdCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblIdCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblIdCliente.setText("ID Cliente:");

        txtIdCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtIdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdClienteActionPerformed(evt);
            }
        });

        lblDescricao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDescricao.setForeground(new java.awt.Color(255, 255, 255));
        lblDescricao.setText("Descricao:");

        txtDescricao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 153, 153));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalvar.setBackground(new java.awt.Color(153, 204, 255));
        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        btnSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSalvarKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnSalvarKeyTyped(evt);
            }
        });

        dc_Inicio.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        dc_Fim.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(dc_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDtaTermino)
                                    .addComponent(lblIdProjetista)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtIdProjetista, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                            .addComponent(dc_Fim, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblNumero)
                                    .addComponent(lblDescricao)
                                    .addComponent(lblIdCliente)
                                    .addComponent(lblDtaInicio)
                                    .addComponent(txtIdCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(txtNumero))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtDescricao)
                                .addGap(6, 6, 6))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblIdProjetista, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdProjetista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(lblDtaTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dc_Fim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addComponent(lblDtaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dc_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16)
                        .addComponent(lblDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelar)
                            .addComponent(btnSalvar))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void txtIdProjetistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProjetistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProjetistaActionPerformed

    private void txtIdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdClienteActionPerformed

    private void txtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoActionPerformed

    private void jt_MostraProjetosProjetistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_MostraProjetosProjetistaMouseClicked
        int row = jt_MostraProjetosProjetista.getSelectedRow();
        txtNumero.setText(jt_MostraProjetosProjetista.getValueAt(row, 0).toString());
        
        DateFormat format = new SimpleDateFormat("yyyy-MM-dd");
 
        try {
            dc_Inicio.setDate(format.parse(jt_MostraProjetosProjetista.getValueAt(row, 1).toString()));
            dc_Fim.setDate(format.parse(jt_MostraProjetosProjetista.getValueAt(row, 2).toString()));
        } catch (ParseException ex) {
            Logger.getLogger(VwJIFProjetoProjetista.class.getName()).log(Level.SEVERE, null, ex);
        }
 
        txtIdProjetista.setText(jt_MostraProjetosProjetista.getValueAt(row, 3).toString());
        txtIdCliente.setText(jt_MostraProjetosProjetista.getValueAt(row, 4).toString());
        txtDescricao.setText(String.valueOf(jt_MostraProjetosProjetista.getValueAt(row, 5)));
        if (txtDescricao.getText().equals("null")){
            txtDescricao.setText("");
        }
        
    }//GEN-LAST:event_jt_MostraProjetosProjetistaMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        this.desabilitaTxt();
        this.limparCampos();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked

        String acaoBotao = Constante.cadastro;
        if(acaoBotao.equals("Novo")){
            try{
            ConexaoBD bd = new ConexaoBD();
            
            conectaBanco(Constante.servidor, bd, Constante.login, Constante.login);
            String sql="INSERT INTO private.projeto(data_inicio, data_termino, id_projetista, id_cliente, descricao)\n" +
                       "VALUES ('"+ dc_Inicio.getDate() +"','"+ dc_Fim.getDate() +"',"
                        + ""+ txtIdProjetista.getText() +","+ txtIdCliente.getText() +", '"+ txtDescricao.getText() +"')";
            
            bd.stmt.executeUpdate(sql);
            bd.Desconectar();
            
            
            JOptionPane.showMessageDialog(null, "Projeto cadastrado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            } 
            
        }else if(acaoBotao.equals("Alterar")){
            try{
                ConexaoBD bd = new ConexaoBD();
                
                conectaBanco(Constante.servidor, bd, Constante.login, Constante.login);
                String sql="UPDATE private.projeto SET data_inicio ='"+ dc_Inicio.getDate() + "', data_termino ='\n" +
                        dc_Fim.getDate() + "', id_projetista ='"+ txtIdProjetista.getText() + "', id_cliente ='\n" +
                        txtIdCliente.getText() + "', descricao ='" + txtDescricao.getText() + "' WHERE numero =" + txtNumero.getText();
                
                bd.stmt.executeUpdate(sql);
                bd.Desconectar();
                
                JOptionPane.showMessageDialog(null, "Projeto atualizado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
          
                }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
                } 
            
        }else if(acaoBotao.equals("Deletar")){
            Object[]opcoes = {"Sim","Não"};
            int opcao = JOptionPane.showOptionDialog(null, "Tem certeza que deseja deletar esse Projeto?", "Aviso", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, opcoes, opcoes[0]);
        
            if(opcao == 0){
            try{
                ConexaoBD bd = new ConexaoBD();
                conectaBanco(Constante.servidor, bd, Constante.login, Constante.login);
                
                String sql= "DELETE FROM private.projeto WHERE numero = " + txtNumero.getText();
                bd.stmt.executeUpdate(sql);
                
                bd.Desconectar();
                JOptionPane.showMessageDialog(null, "Projeto deletado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                
                }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
             } 
           }   
        }
        
        this.atualizaDataTable();
        
        limparCampos();
        acaoBotao = "";
        this.desabilitaTxt();
    }//GEN-LAST:event_btnSalvarMouseClicked
    
    private void atualizaDataTable() {
        DefaultTableModel model = (DefaultTableModel) jt_MostraProjetosProjetista.getModel();

        model.setRowCount(0);
        /**/
        ArrayList<Projeto> list = projetoList();

        Object[] row = new Object[6];
            for(int i=0; i<list.size();i++){
                row[0]=list.get(i).getNumero();
                row[1]=list.get(i).getData_inicio();
                row[2]=list.get(i).getData_termino();
                row[3]=list.get(i).getId_projetista();
                row[4]=list.get(i).getId_cliente();
                row[5]=list.get(i).getDescricao();
                model.addRow(row);
            }
        jt_MostraProjetosProjetista.setModel(model);
  
        model.fireTableDataChanged();

}
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSalvarKeyPressed

    }//GEN-LAST:event_btnSalvarKeyPressed

    private void btnSalvarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSalvarKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarKeyTyped

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        this.txtNumero.setEnabled(false);
        this.desabilitaTxt();
       

        try{
            ArrayList<Projeto> list = projetoList();
            txtIdProjetista.setText(Integer.toString(list.get(0).getId_projetista()));
        }catch(Exception e){
            
        } 
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoMouseClicked
        this.habilitaTxt();
        Constante.cadastro = "Novo"; 
        limparCampos();
    }//GEN-LAST:event_btnNovoMouseClicked

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
        this.habilitaTxt();
        Constante.cadastro = "Alterar";
    }//GEN-LAST:event_btnEditarMouseClicked

    private void btnDeletarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeletarMouseClicked
        Constante.cadastro = "Deletar";
        this.btnSalvarMouseClicked(evt);
    }//GEN-LAST:event_btnDeletarMouseClicked

     private void habilitaTxt(){
        this.txtDescricao.setEnabled(true);
        this.dc_Inicio.setEnabled(true);
        this.dc_Fim.setEnabled(true);
        this.txtIdCliente.setEnabled(true);
        //this.txtIdProjetista.setEnabled(true);
      
    }
    
    private void desabilitaTxt(){
        this.txtDescricao.setEnabled(false);
        this.dc_Inicio.setEnabled(false);
        this.dc_Fim.setEnabled(false);
        this.txtIdCliente.setEnabled(false);
        this.txtIdProjetista.setEnabled(false);
    }
    
    private void limparCampos(){
        this.txtDescricao.setText("");
        this.dc_Inicio.setDate(null);
        this.dc_Fim.setDate(null);
        this.txtIdCliente.setText("");
        //this.txtIdProjetista.setText("");
        this.txtNumero.setText("");
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private com.toedter.calendar.JDateChooser dc_Fim;
    private com.toedter.calendar.JDateChooser dc_Inicio;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jt_MostraProjetosProjetista;
    private javax.swing.JToolBar jtb_botoes;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblDtaInicio;
    private javax.swing.JLabel lblDtaTermino;
    private javax.swing.JLabel lblIdCliente;
    private javax.swing.JLabel lblIdProjetista;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtIdProjetista;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables



}
